sudo: false
dist: trusty
language: node_js
node_js:
  - "8.5.0"

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
     - ./node_modules
     - ./.chrome/chromium

git:
  depth: 1

script:
  - npm run test
  - npm run test-coverage

after_success:
  - ./node_modules/.bin/codecov
