sudo: required
language: node_js
node_js:
  - "8.5.0"

addons:
  chrome: stable

git:
  depth: 1

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm@~5.3.0

install:
  - npm install

script:
  - npm run fix-v6
  - npm run test-coverage

after_success:
  - ./node_modules/.bin/codecov

