sudo: false
language: node_js
node_js:
  - "8.5.0"

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test
  - npm run test-coverage

after_success:
  - ./node_modules/.bin/codecov
